'use client';
// Auto-generated by cro. Initializes PostHog autocapture using the App ID and
// public key in cro.config.json. Safe to commit; the public key is meant for
// client-side use.
import { useEffect } from 'react';
import config from '../cro.config.json';

let initialized = false;

export function CroTracker() {
  useEffect(() => {
    if (initialized || typeof window === 'undefined') return;
    if (!config.posthog_key) return;
    initialized = true;
    void (async () => {
      const posthog = (await import('posthog-js')).default;
      posthog.init(config.posthog_key, {
        api_host: config.posthog_host || 'https://us.i.posthog.com',
        capture_pageview: !!config.capture.route,
        autocapture: !!config.capture.click,
        person_profiles: 'identified_only',
        loaded: (ph) => {
          (ph as unknown as { register: (p: Record<string, unknown>) => void }).register({
            cro_app_id: config.app_id,
          });
        },
      });
    })();
  }, []);
  return null;
}
