/**
 * Auto-instrumentation event catalog.
 *
 * Generated by cro. Maintained by the agent on every push — when behavior
 * changes (handler text, element type), the event definitions update so
 * your PostHog taxonomy stays aligned with what the UI actually does.
 *
 * Usage:
 *   import { capture, type CroEvent } from './events';
 *   capture('checkout_button_clicked', { source_file: '...' });
 */

import { z } from 'zod';

export const BUTTON_CLICKED_SCHEMA = z.object({
  source_file: z.string(),
  element: z.string(),
});

export const SHOW_QR_CLICKED_SCHEMA = z.object({
  source_file: z.string(),
  element: z.string(),
  label: z.string(),
});

export const BUTTON_CLICKED_SETUP_SCHEMA = z.object({
  source_file: z.string(),
  element: z.string(),
});

export const OPEN_IN_NEW_TAB_CLICKED_SCHEMA = z.object({
  source_file: z.string(),
  element: z.string(),
  label: z.string(),
});

export const BTCPAY_SERVER_INFORMATION_SUBMITTED_SCHEMA = z.object({
  source_file: z.string(),
  element: z.string(),
  label: z.string(),
});

export const CANCEL_CLICKED_SCHEMA = z.object({
  source_file: z.string(),
  element: z.string(),
  label: z.string(),
});

export const ACCOUNT_INFORMATION_SUBMITTED_SCHEMA = z.object({
  source_file: z.string(),
  element: z.string(),
  label: z.string(),
});

export const CANCEL_CLICKED_SETUP_SCHEMA = z.object({
  source_file: z.string(),
  element: z.string(),
  label: z.string(),
});

export const CONFIGURE_STEP_CARD_SUBMITTED_SCHEMA = z.object({
  source_file: z.string(),
  element: z.string(),
});

export const BUTTON_CLICKED_CONFIRMDIALOG_SCHEMA = z.object({
  source_file: z.string(),
  element: z.string(),
});

export const WIPE_TODAY_CLICKED_SCHEMA = z.object({
  source_file: z.string(),
  element: z.string(),
  label: z.string(),
});

export const FORM_SUBMITTED_SCHEMA = z.object({
  source_file: z.string(),
  element: z.string(),
});

export const BUTTON_CLICKED_ADDGUESTSDIALOG_SCHEMA = z.object({
  source_file: z.string(),
  element: z.string(),
});

export const BUTTON_CLICKED_REJECTIONREASONDIALOG_SCHEMA = z.object({
  source_file: z.string(),
  element: z.string(),
});

export const FORM_SUBMITTED_REPORTBOOKINGDIALOG_SCHEMA = z.object({
  source_file: z.string(),
  element: z.string(),
});

export const BUTTON_CLICKED_RESCHEDULEDIALOG_SCHEMA = z.object({
  source_file: z.string(),
  element: z.string(),
});

export const BUTTON_CLICKED_WRONGASSIGNMENTDIALOG_SCHEMA = z.object({
  source_file: z.string(),
  element: z.string(),
});

export const FORM_SUBMITTED_WRONGASSIGNMENTDIALOG_SCHEMA = z.object({
  source_file: z.string(),
  element: z.string(),
});

export const CONTACT_SUPPORT_CLICKED_SCHEMA = z.object({
  source_file: z.string(),
  element: z.string(),
  label: z.string(),
});

export const FORM_SUBMITTED_USERPROFILE_SCHEMA = z.object({
  source_file: z.string(),
  element: z.string(),
});

export const EVENTS = {
  button_clicked: BUTTON_CLICKED_SCHEMA,
  show_qr_clicked: SHOW_QR_CLICKED_SCHEMA,
  button_clicked_setup: BUTTON_CLICKED_SETUP_SCHEMA,
  open_in_new_tab_clicked: OPEN_IN_NEW_TAB_CLICKED_SCHEMA,
  btcpay_server_information_submitted: BTCPAY_SERVER_INFORMATION_SUBMITTED_SCHEMA,
  cancel_clicked: CANCEL_CLICKED_SCHEMA,
  account_information_submitted: ACCOUNT_INFORMATION_SUBMITTED_SCHEMA,
  cancel_clicked_setup: CANCEL_CLICKED_SETUP_SCHEMA,
  configure_step_card_submitted: CONFIGURE_STEP_CARD_SUBMITTED_SCHEMA,
  button_clicked_confirmdialog: BUTTON_CLICKED_CONFIRMDIALOG_SCHEMA,
  wipe_today_clicked: WIPE_TODAY_CLICKED_SCHEMA,
  form_submitted: FORM_SUBMITTED_SCHEMA,
  button_clicked_addguestsdialog: BUTTON_CLICKED_ADDGUESTSDIALOG_SCHEMA,
  button_clicked_rejectionreasondialog: BUTTON_CLICKED_REJECTIONREASONDIALOG_SCHEMA,
  form_submitted_reportbookingdialog: FORM_SUBMITTED_REPORTBOOKINGDIALOG_SCHEMA,
  button_clicked_rescheduledialog: BUTTON_CLICKED_RESCHEDULEDIALOG_SCHEMA,
  button_clicked_wrongassignmentdialog: BUTTON_CLICKED_WRONGASSIGNMENTDIALOG_SCHEMA,
  form_submitted_wrongassignmentdialog: FORM_SUBMITTED_WRONGASSIGNMENTDIALOG_SCHEMA,
  contact_support_clicked: CONTACT_SUPPORT_CLICKED_SCHEMA,
  form_submitted_userprofile: FORM_SUBMITTED_USERPROFILE_SCHEMA,
} as const;

export type CroEventName = keyof typeof EVENTS;
export type CroEventProps<K extends CroEventName> = z.infer<(typeof EVENTS)[K]>;

/**
 * Type-safe wrapper around your analytics provider's capture call.
 * Generated against the provider detected in package.json. Adjust if needed.
 */
export type CroEvent = {
  [K in CroEventName]: { name: K; props: CroEventProps<K> };
}[CroEventName];

export function capture<K extends CroEventName>(name: K, props: CroEventProps<K>): void {
  // Validate at the boundary so a typo can't ship to PostHog.
  EVENTS[name].parse(props);
  if (typeof window !== 'undefined' && (window as unknown as { posthog?: { capture: (n: string, p: unknown) => void } }).posthog) {
    (window as unknown as { posthog: { capture: (n: string, p: unknown) => void } }).posthog.capture(name, props);
  }
}
